### ISSUE TITLE
No chart rending...

### ISSUE THREAD

**Issue by wxs77577** [vue-bulma/chartjs#7]
It seems `npm install vue-bulma-chartjs` installs an version for vue 1.x
so I modify my `package.json` > `dependencies` like this:
`"vue-bulma-chartjs": "git+https://github.com/vue-bulma/chartjs.git"`
And run `npm install vue-bulma-chartjs`

Problem solved.

**Comment by JhinDeng** [comment]
thanks

**Comment by lrh-me** [comment]
thanks a lot!  same problem

**Comment by luventa** [comment]
Thanks.
Also, this issue can be solved by using Git Bash
[Git For Windows](https://git-for-windows.github.io/)
[Git For Mac](https://git-scm.com/download/mac)

I will find out if it's published or not, And `package.json` will use version instead of use git/http link to avoid this issue for the future.
